export const headlineSets = [
  {
    id: 'rates-and-policy',
    label: 'Rates and policy',
    headlines: [
      {
        id: 'treasury-yields-dollar-iran-diplomacy',
        source: 'WSJ',
        category: 'Macro',
        title: 'U.S. Treasury yields rise; dollar weakens on U.S.-Iran diplomacy hopes',
        summary:
          'Treasury yields rose as traders watched short-end rate expectations, oil flows, and the week ahead for jobs data.',
        publishedAt: '2026-06-29T09:56:00Z',
        timeLabel: 'Today',
        url: 'https://www.wsj.com/finance/investing/jgbs-fall-amid-rising-crude-oil-prices-05747839',
        featured: true,
        priority: 1,
      },
      {
        id: 'us-treasury-yields-hormuz',
        source: 'Barron\'s',
        category: 'Treasuries',
        title: 'U.S. Treasury yields rise, focus remains on ship traffic in Strait of Hormuz',
        summary:
          'Short-end yields led a modest move higher as traders watched rate expectations and geopolitical risk around energy flows.',
        publishedAt: '2026-06-29T07:10:28Z',
        timeLabel: 'Today',
        url: 'https://www.barrons.com/livecoverage/stock-market-news-today-062926/card/u-s-treasury-yields-rise-focus-remains-on-ship-traffic-in-strait-of-hormuz-KCtxwInA342KCtlZMxit',
        featured: true,
        priority: 2,
      },
      {
        id: 'warsh-fed-talk-bond-yields',
        source: 'MarketWatch',
        category: 'Rates',
        title: "Bond yields are falling as inflation pops. The Fed's tough talk under Warsh is helping.",
        summary:
          'Treasury yields moved lower as investors weighed inflation data against a firmer central bank policy message.',
        publishedAt: '2026-06-27T20:38:00Z',
        timeLabel: '2 days ago',
        url: 'https://www.marketwatch.com/story/bond-yields-are-falling-as-inflation-pops-the-feds-tough-talk-under-warsh-is-helping-7d538b3b',
        featured: true,
        priority: 3,
      },
      {
        id: 'us-bond-market-rises-yields-fall',
        source: 'MarketWatch',
        category: 'Bond Funds',
        title: 'U.S. bond market rises as Treasury yields fall',
        summary:
          'Bond ETFs advanced as Treasury yields declined and investors digested inflation data near expectations.',
        publishedAt: '2026-06-26T15:30:00Z',
        timeLabel: '3 days ago',
        url: 'https://www.marketwatch.com/livecoverage/stock-market-today-dow-s-p-500-nasdaq-micron-earnings-results-pce-inflation-data/card/u-s-bond-market-rises-as-treasury-yields-fall-TN9gu42L5lb3nHdi4MwM',
        featured: true,
        priority: 4,
      },
      {
        id: 'treasury-yields-fall-oil-prices',
        source: 'WSJ',
        category: 'Rates',
        title: 'Treasury yields fall with oil prices',
        summary:
          'A pullback in energy prices helped ease inflation worries, pulling Treasury yields lower across the curve.',
        publishedAt: '2026-06-25T14:31:15Z',
        timeLabel: '4 days ago',
        url: 'https://www.wsj.com/livecoverage/stock-market-today-dow-sp-500-nasdaq-06-24-2026/card/treasury-yields-fall-with-oil-prices-pfdPLGxlC2iN7WnP4q1x',
      },
      {
        id: 'two-year-yield-curve-flattens',
        source: 'MarketWatch',
        category: 'Yield Curve',
        title: '2-year Treasury yield hits highest settlement since February 2025 as yield curve flattens',
        summary:
          'Policy-sensitive short-dated yields rose as the spread between 30-year and 2-year Treasurys narrowed.',
        publishedAt: '2026-06-23T20:31:29Z',
        timeLabel: '6 days ago',
        url: 'https://www.marketwatch.com/livecoverage/stock-market-today-dow-s-p-500-investors-us-iran-peace-talks-brent-crude-declines/card/2-year-treasury-yield-hits-highest-settlement-since-february-2025-as-yield-curve-flattens-35uNfQk6m37gVKipRvKd',
      },
      {
        id: 'bond-market-volatility-here-to-stay',
        source: 'MarketWatch',
        category: 'Volatility',
        title: "The bond market just did something unusual. Why its sudden volatility is here to stay.",
        summary:
          'Rates strategists pointed to shifting central bank communication and larger intraday swings in Treasury trading.',
        publishedAt: '2026-06-23T20:03:00Z',
        timeLabel: '6 days ago',
        url: 'https://www.marketwatch.com/story/the-bond-market-just-did-something-unusual-why-its-sudden-volatility-is-here-to-stay-a60205ff',
      },
    ],
  },
  {
    id: 'credit-and-supply',
    label: 'Credit and supply',
    headlines: [
      {
        id: 'nvidia-bond-sale-treasury-yields',
        source: 'WSJ',
        category: 'Corporate Supply',
        title: 'Jumbo bond sale from Nvidia helps prop up Treasury yields',
        summary:
          'A large corporate bond issue added to supply pressure as investors compared corporate debt with government bonds.',
        publishedAt: '2026-06-15T20:04:03Z',
        timeLabel: 'Last week',
        url: 'https://www.wsj.com/livecoverage/stock-market-today-dow-sp-500-nasdaq-06-15-2026/card/jumbo-bond-sale-from-nvidia-helps-prop-up-treasury-yields-RLVEAcHl9i57ul4tGP9H',
        featured: true,
        priority: 1,
      },
      {
        id: 'rising-bond-yields-stock-market',
        source: 'Barron\'s',
        category: 'Equity Impact',
        title: "Rising bond yields are becoming the stock market's biggest problem",
        summary:
          'Higher Treasury yields complicated the equity backdrop as traders recalibrated expectations for policy rates.',
        publishedAt: '2026-06-23T12:30:00Z',
        timeLabel: '6 days ago',
        url: 'https://www.barrons.com/articles/bond-yields-stock-market-problem-4d2ca0b8',
        featured: true,
        priority: 2,
      },
      {
        id: 'bond-spreads-yearly-highs',
        source: 'Barron\'s',
        category: 'Credit',
        title: 'Yields dive below 4%, bond spreads hit yearly highs as traders get spooked',
        summary:
          'Treasurys rallied while credit spreads widened, highlighting a split between government bonds and corporate debt.',
        publishedAt: '2026-02-27T18:30:00Z',
        timeLabel: '4 months ago',
        url: 'https://www.barrons.com/articles/bond-yields-treasuries-corporate-spread-740caef4',
        featured: true,
        priority: 3,
      },
      {
        id: 'ig-credit-spreads-monitor',
        source: 'FRED',
        category: 'Credit',
        title: 'Investment-grade spreads remain a key screen for portfolio risk appetite',
        summary:
          'Credit desks are comparing all-in yields with spread compensation as issuance and fund flows shape allocation.',
        publishedAt: '2026-06-28T13:00:00Z',
        timeLabel: 'Yesterday',
        url: 'https://fred.stlouisfed.org/series/BAMLC0A0CM',
        featured: true,
        priority: 4,
      },
      {
        id: 'corporate-refinancing-window',
        source: 'FINRA',
        category: 'Corporate Bonds',
        title: 'Borrowers monitor refinancing windows as higher coupons reset capital plans',
        summary:
          'Treasurers and credit investors are watching maturity walls, call schedules, and primary-market concessions.',
        publishedAt: '2026-06-27T12:00:00Z',
        timeLabel: '2 days ago',
        url: 'https://www.finra.org/finra-data/fixed-income',
      },
      {
        id: 'high-yield-dispersion',
        source: 'FRED',
        category: 'High Yield',
        title: 'High-yield dispersion keeps sector selection ahead of broad beta trades',
        summary:
          'Managers are separating defensive carry from lower-quality refinancing risk as default assumptions diverge.',
        publishedAt: '2026-06-24T16:00:00Z',
        timeLabel: '5 days ago',
        url: 'https://fred.stlouisfed.org/series/BAMLH0A0HYM2',
      },
      {
        id: 'primary-market-calendar',
        source: 'SIFMA',
        category: 'Issuance',
        title: 'Primary-market calendars remain central to credit spread discussions',
        summary:
          'Syndicate desks continue to watch issuance windows, investor demand, and new-issue concessions across sectors.',
        publishedAt: '2026-06-21T13:30:00Z',
        timeLabel: 'Last week',
        url: 'https://www.sifma.org/resources/research/us-corporate-bonds-statistics/',
      },
    ],
  },
  {
    id: 'global-and-funds',
    label: 'Global and funds',
    headlines: [
      {
        id: 'bis-sovereign-bond-stability-warning',
        source: 'The Times',
        category: 'Sovereign Risk',
        title: 'Global central bank warns of Liz Truss-style bonds crisis',
        summary:
          'The Bank for International Settlements warned that leverage and public debt could amplify stress in government bond markets.',
        publishedAt: '2026-06-28T09:00:00Z',
        timeLabel: 'Yesterday',
        url: 'https://www.thetimes.com/business/economics/article/liz-truss-bond-crisis-bis-s8wj3tm39',
        featured: true,
        priority: 1,
      },
      {
        id: 'uk-gilt-yields-pmi-data',
        source: 'WSJ',
        category: 'Global Bonds',
        title: 'Gilt yields fall; focus on U.K. PMI data',
        summary:
          'U.K. government bond yields eased while investors watched economic data and public-finance concerns.',
        publishedAt: '2026-06-23T07:35:00Z',
        timeLabel: '6 days ago',
        url: 'https://www.wsj.com/finance/investing/jgb-futures-fall-tracking-declines-in-u-s-treasury-market-fe9eb621',
        featured: true,
        priority: 2,
      },
      {
        id: 'municipal-bond-funds',
        source: 'MSRB',
        category: 'Municipals',
        title: 'Municipal bond funds stay in focus as tax-aware income screens widen',
        summary:
          'Advisors are comparing taxable-equivalent yields, state exposure, and duration risk across muni allocations.',
        publishedAt: '2026-06-27T15:00:00Z',
        timeLabel: '2 days ago',
        url: 'https://emma.msrb.org/',
        featured: true,
        priority: 3,
      },
      {
        id: 'global-policy-paths',
        source: 'BIS',
        category: 'Global Rates',
        title: 'Sovereign markets trade around diverging policy paths',
        summary:
          'Global rates desks are tracking currency moves, fiscal plans, and inflation expectations across developed markets.',
        publishedAt: '2026-06-29T08:15:00Z',
        timeLabel: 'Today',
        url: 'https://www.bis.org/statistics/secstats.htm',
        featured: true,
        priority: 4,
      },
      {
        id: 'core-bond-etf-demand',
        source: 'Vanguard',
        category: 'Funds',
        title: 'Core bond ETF demand reflects renewed focus on portfolio income',
        summary:
          'Flows remain concentrated in short-duration and aggregate bond products as allocators review cash alternatives.',
        publishedAt: '2026-06-26T10:30:00Z',
        timeLabel: '3 days ago',
        url: 'https://investor.vanguard.com/investment-products/etfs/bond-etfs',
      },
      {
        id: 'securitized-credit-watch',
        source: 'SIFMA',
        category: 'Structured Credit',
        title: 'Securitized credit desks track consumer data and collateral performance',
        summary:
          'Relative-value discussions are centered on spreads, prepayment assumptions, and protection against weaker credit trends.',
        publishedAt: '2026-06-24T11:00:00Z',
        timeLabel: '5 days ago',
        url: 'https://www.sifma.org/resources/research/us-asset-backed-securities-statistics/',
      },
      {
        id: 'international-debt-securities',
        source: 'BIS',
        category: 'Global Bonds',
        title: 'International debt securities data frames cross-border bond supply',
        summary:
          'Global fixed-income desks use international issuance data to compare sovereign, financial, and corporate supply trends.',
        publishedAt: '2026-06-20T12:00:00Z',
        timeLabel: 'Last week',
        url: 'https://www.bis.org/statistics/secstats.htm',
      },
    ],
  },
]
